CREATE TABLE IF NOT EXISTS reunioes_blackcrm (
  id_unico             text PRIMARY KEY,
  id_reuniao           text,
  id_cliente           text,
  codigo_cliente       numeric,
  empresa              text,
  nome_empresa_formatado text,
  data_reuniao         text,
  horario              text,
  mes                  numeric,
  semana               numeric,
  ano                  numeric,
  inicio_semana        text,
  fim_semana           text,
  tipo_reuniao         text CHECK (tipo_reuniao IN ('implementacao', 'tutoria')),
  responsavel          text,
  nps                  numeric,
  transcricao          text,
  transcricao_md       text,
  resumo               text,
  resumo_json          text,
  acoes                text,
  link_gravacao        text,
  link_geminidoc       text,
  status_match         text,
  metodo_match         text,
  observacoes          text,
  created_at           text DEFAULT to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS')
);
